version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "20"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
