#!/usr/bin/env python

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

from nbdime.application import main_nbpatch

if __name__ == '__main__':
    main_nbpatch()
