#!/usr/bin/env python

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

from nbmerge.application import main_nbmerge

if __name__ == '__main__':
    main_nbmerge()
