#!/usr/bin/env python
# coding: utf-8

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

from __future__ import print_function

if __name__ == "__main__":
    print("Dummy script until nbmerge is implemented.")
